# Site settings
title: Daniel Electronics
email: daniel@danielelectronics.com # get this email
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my webiste, a place where I write about my projects, hobbies, gadgets, and whatever else I feel like writing about.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://danielelectronics.com" # the base hostname & protocol for your site, e.g. http://example.com
# Put usernames here for Youtube and GitHub

# Build settings
markdown: kramdown

highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 2
paginate_path: "/blog/page:num/"

# Exclude from processing.
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
